import React from 'react'

export default function Bai6() {
  return (
    <div>
      <div className='overflow-auto h-52 w-125 border border-gray-400 p-4 bg-white'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Placeat laudantium ex dignissimos odio, natus, cupiditate harum totam veritatis temporibus nulla alias delectus quod mollitia aliquam, eaque debitis cum dicta doloremque!
      Dolor, blanditiis laborum quo ut quae consequuntur quibusdam voluptatibus saepe voluptatum facilis iusto eaque tempora minima laboriosam asperiores velit consectetur incidunt quis sint eveniet eius quos ratione harum! Tenetur, non?
      Illo sed enim blanditiis quae consequatur minima consequuntur animi alias voluptates nam ex, harum quos cumque laboriosam perferendis! Autem facere placeat accusantium non natus tempore nulla optio, id reprehenderit totam?
      Repellat, minus eius laboriosam ab ipsum atque mollitia corporis aperiam veritatis fugit accusamus architecto ratione impedit quaerat aut saepe repellendus est cum. Illo enim autem iste omnis quas, deleniti perferendis!
      Perspiciatis quibusdam molestiae tempore eaque cumque ducimus! Repellat ut cum corporis, neque fugiat magni hic accusamus ea dolorem aliquam, quisquam voluptate harum nisi placeat vitae explicabo non! Fugiat, rerum ducimus?
      Non fugit quasi quidem quas ipsum excepturi tempora molestias qui recusandae repellat? Voluptas, sapiente harum, aperiam possimus ratione et quasi voluptates labore aspernatur obcaecati officiis dolorum autem illum, praesentium voluptatem.
      Illum cum nihil perferendis minima debitis quis nesciunt, laborum enim repellat dicta voluptates sit? Dolore sunt quas vitae reprehenderit, sequi quis, cum libero, ipsam laudantium fuga sapiente voluptates dolores similique.
      Est temporibus, tenetur, pariatur sapiente velit sit ducimus modi accusantium voluptate corporis doloremque cumque. Dolor, sapiente quae accusamus reprehenderit fugit repellendus voluptate nostrum repudiandae tempore corporis assumenda expedita rerum a.
      Error, tenetur? Ipsam, itaque. Perferendis sit, expedita ad odit alias fuga tempora, dolore qui facilis, cupiditate eos voluptate quis officia corporis! Molestias eos perspiciatis accusamus quia placeat atque facilis dolore?
      Consequatur ea maxime inventore sapiente fugiat, ipsum assumenda voluptas corporis necessitatibus officiis aperiam nisi temporibus ullam quibusdam consectetur in molestiae! Soluta perspiciatis eius fugiat maxime unde culpa in sint voluptates.
      Obcaecati ratione expedita esse beatae accusantium aut iste facilis quae dolorum explicabo ipsam vel animi a, repellat atque qui ad quasi modi corporis quis minus, hic nisi. Eveniet, beatae deleniti?
      Necessitatibus provident a corporis debitis ullam nulla consequuntur neque quisquam nesciunt ducimus in molestiae repellendus similique totam obcaecati ipsum quia adipisci, ab quidem libero eaque iusto vel sunt! Fugiat, quas.
      Provident laboriosam, voluptas enim quasi nisi maxime magnam nulla consequuntur nam reiciendis itaque iure eligendi ab ex minima beatae, saepe animi, odit magni veritatis ipsam similique nostrum natus quisquam. Quis.
      Dolore omnis, voluptatibus vel alias placeat aliquid sapiente? Velit earum, dolor nostrum, architecto natus maxime atque totam nulla molestiae laborum provident consequatur amet nam. Pariatur fugit exercitationem velit error suscipit.
      Ex ea at aspernatur ut odio officia quos tempora, cupiditate hic odit nostrum, alias placeat unde eveniet adipisci illo dignissimos natus atque rem incidunt vero? Earum cupiditate in ea quis.
      Ex nostrum quis pariatur veritatis corporis eius architecto modi saepe voluptatum amet cumque, ratione consequuntur soluta alias magni. Rerum reiciendis saepe minus cupiditate, velit laborum. Accusantium atque dolore aliquid nesciunt!
      Iste alias sint maxime nihil. Cumque harum totam asperiores. Consequatur nemo praesentium porro rerum natus non autem quos cum distinctio ullam sapiente sit corporis similique, harum, nesciunt, ut cumque placeat.
      Temporibus deleniti labore quasi ratione aliquam officiis voluptas, ad sint molestiae beatae quia eveniet recusandae, placeat animi nam. Distinctio exercitationem vel laborum ratione dolor harum? Magnam iusto enim cum architecto.
      Consequuntur sunt qui corrupti ex. Qui, doloremque. Quod qui laborum earum, in optio quam nihil aspernatur nulla quia omnis, animi quos saepe voluptate voluptas veritatis. Quis sed omnis iste quisquam.
      Officiis, eaque nobis! Voluptatum maxime sequi nesciunt sit repellendus perferendis dolorum, deserunt inventore quasi, cum quae laborum labore rem quo fugiat veniam est! Error consequatur aperiam doloribus quo expedita sequi?
      Reiciendis tenetur ex, ullam in recusandae quo molestias accusantium debitis at eius ut consequuntur doloribus itaque inventore quasi nobis dolore praesentium quia doloremque quos asperiores. Veniam ipsam quaerat atque alias.
      Tempore dicta eaque earum in illo cupiditate animi minus ex doloremque, cumque, quis suscipit saepe tenetur ducimus assumenda fuga error, perspiciatis quasi nemo maiores impedit quisquam veritatis nobis expedita. Officiis?
      Consectetur nam neque laboriosam quisquam id cupiditate officia, unde saepe. Nostrum iure autem, quae perspiciatis atque consequuntur quos facere esse, molestias itaque ipsa. Ratione aliquam impedit nihil quae quibusdam cupiditate.
      Aliquam, cumque! Quos laboriosam dolore impedit quae? Eligendi iusto porro quis placeat reprehenderit eos, culpa quos explicabo dolor ab! Debitis, fugit qui. Dolorum ipsum accusantium fugiat sint, voluptatibus laudantium atque!
      Corrupti quia qui ullam enim, molestiae obcaecati est eos quam ipsum incidunt. Ex, at veritatis laborum neque assumenda, rem ullam similique, aut dolores molestiae aspernatur iusto nesciunt quae numquam voluptate!
      Cumque quas sed autem voluptate earum quos cum, illum consequuntur dicta, consequatur atque ex et id quia ratione alias in nam. Nostrum animi aut veniam, adipisci doloribus culpa temporibus numquam.
      Eveniet debitis quod sunt iure, possimus tempora voluptas illum, dicta facilis harum accusamus placeat ea consequuntur beatae veniam ipsa temporibus iusto magni sit perferendis dignissimos! Rerum eius possimus temporibus hic!
      Quas, dolore adipisci! Tempora aut tenetur cum eveniet ut alias ducimus est velit illum, omnis, consequuntur consectetur fugit, incidunt asperiores delectus possimus corrupti numquam qui saepe vel fugiat quidem magni.
      Nulla facere odit inventore reiciendis assumenda porro facilis officiis illo officia doloremque. Delectus ducimus perspiciatis veniam aut exercitationem. Quia nostrum error dolores quo at accusamus vitae, expedita magni ipsam consectetur?
      Ipsum harum repudiandae consectetur minus amet saepe unde laboriosam ut voluptates totam quo expedita nisi sint magnam laborum facere soluta voluptatem et, illum repellendus quas, natus dolor autem magni. Odio!
      Earum perferendis minus consequuntur quo ut? Atque minus qui quae deserunt inventore voluptatem! Odit, cumque incidunt dignissimos voluptatem ab sequi enim impedit nisi laudantium quidem ad! Fugiat ullam distinctio at!
      Magnam dolores molestiae doloribus nulla accusamus atque deleniti minus laboriosam mollitia amet neque expedita optio quibusdam, sit rerum soluta. Provident culpa mollitia quia nobis ullam placeat repudiandae eaque pariatur illum.
      Commodi harum vel numquam ex tempore tempora accusamus repellendus quisquam iusto nostrum temporibus ab asperiores dolorem cum doloremque vero est veritatis vitae sed deserunt eveniet, provident quasi ratione autem. Laborum.
      Quaerat cupiditate tenetur quisquam optio. Expedita distinctio maiores minus iste quam incidunt pariatur quae qui dolorem corrupti quaerat voluptatem iure animi molestiae, alias adipisci quibusdam earum dolor. Autem, nisi quod!
      Cumque sit eaque natus illum excepturi ea nam inventore ratione consectetur libero, quasi dolorem asperiores esse neque? Rerum, laboriosam. Sed minus placeat ex molestiae atque porro tenetur suscipit iusto excepturi.
      Officiis, quos quis. Qui temporibus consequatur est asperiores nobis, doloremque ducimus omnis ea dolor aliquid veritatis deserunt amet, laudantium ipsa expedita nulla! Nemo sunt, tenetur sequi perferendis neque quae aspernatur?
      Possimus ipsum amet officiis cupiditate commodi dignissimos distinctio assumenda, illum tenetur porro. Aut facere atque, in repellendus ullam ratione est veniam saepe sunt molestiae praesentium quod magni, magnam corrupti ducimus!
      Reprehenderit numquam, magni nemo provident magnam nulla suscipit similique aspernatur modi soluta exercitationem obcaecati molestias, commodi ratione. Quibusdam amet fugiat nobis beatae quaerat adipisci, tempore sequi, possimus, tempora facilis vitae.
      Odio vitae nostrum, tempora illum commodi similique eaque alias ducimus deserunt minima non veritatis illo debitis placeat architecto labore corporis rem culpa id. Molestias, rem suscipit itaque est fugiat perferendis?
      Repellat ad incidunt sint, omnis voluptatibus repellendus qui ipsam. Consectetur mollitia eum modi adipisci eligendi nihil recusandae hic cumque ducimus voluptatum minus delectus officia, perferendis quae, non iusto nulla reprehenderit.
      Quos reprehenderit, veniam ab modi similique quia iusto mollitia iure, ducimus autem sit nulla impedit est quisquam placeat eaque eveniet quis error dolore? In commodi dolores fugiat consequuntur. Libero, maiores.
      Voluptates voluptatem necessitatibus ex asperiores inventore soluta atque suscipit, ratione qui quos non iure nulla est magnam beatae. Dolorem, cupiditate. Ullam, id! Nesciunt reprehenderit, esse repellat sequi sint inventore quas.
      Ab, reiciendis labore nihil corrupti obcaecati adipisci dolorum libero iusto quos quasi dolore debitis, eveniet nemo, excepturi suscipit quam placeat. Id soluta, impedit earum excepturi eaque omnis tempora illum in?
      Ipsum, dolor? Cumque adipisci libero laudantium amet dolorum corporis ducimus delectus repellendus quos maxime aspernatur hic eligendi porro dicta, repudiandae magnam est pariatur neque ab alias? Debitis est nobis eum!
      Soluta quas maiores quos officia esse, minima nobis rem at autem quia repellendus, quasi quod, consequuntur et ea architecto odio. Dicta earum in laudantium tenetur pariatur sequi dolores aliquid numquam.
      Corrupti eligendi necessitatibus id magni amet vel tempora nihil maiores mollitia, ex sunt. Necessitatibus alias facilis quam doloremque illum, architecto dolore? Dolorem doloribus non aliquam, aperiam sunt odit deserunt cum.
      Soluta exercitationem dolore hic ipsum sunt blanditiis voluptas dolores alias tenetur nisi! Mollitia ipsum tempore deleniti excepturi magnam odio, cumque in harum quibusdam fugit nihil. Sed aperiam molestiae obcaecati quo.
      Qui quia eius doloribus. Dolorum quia esse id commodi excepturi voluptatibus ad ratione doloremque, est perferendis soluta reprehenderit? Alias ullam ipsa at enim, corporis distinctio consequatur eveniet placeat numquam aut.
      Ullam cum provident voluptates inventore temporibus fuga vel, eligendi harum fugiat minus reprehenderit sunt recusandae quibusdam quod! Odio, maiores magni consequuntur consequatur adipisci suscipit deserunt distinctio deleniti blanditiis commodi nostrum!
      Possimus fugiat provident natus, ratione ipsam magnam quos esse. Sed, deleniti. Voluptatem quidem nesciunt ut eos maxime optio. Beatae dolore temporibus sunt totam ratione ut accusantium dicta porro unde perferendis?</div>
    </div>
  )
}
